use_frameworks!

target 'LiveObjectTracer_Example' do
  pod 'LiveObjectTracer', :path => '../'

  target 'LiveObjectTracer_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
