use_frameworks!

target 'LiveObjectTracer_Example' do
  platform :ios, '12.0'
  pod 'LiveObjectTracer', :path => '../'

  target 'LiveObjectTracer_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
